runtime: custom
env: flex
service: default
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 120
  max_concurrent_requests: 1
  target_concurrent_requests: 2
env_variables:
  CACHE_DIR: "/tmp/cache"
  MAX_CACHE: "100"
  MAX_TIMEOUT: "30"
readiness_check:
  path: "/"
  check_interval_sec: 4
  timeout_sec: 1
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 4
  success_threshold: 2
network:
  forwarded_ports:
    - 8088
